version: '2.0'

services:

  users-service:
    container_name: users-service
    build: .
    volumes:
      - '.:/usr/src/asdf'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=asdf.config.DevelopmentConfig
