version: '2.1'
services:
  flaskangular-db:
    container_name: asdf-db
    build: ./app/db
    ports:
      - 5435:5432 # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0
  flaskangular-service:
    container_name: flaskangular-service
    build: ./
    volumes:
      - '.:/usr/src/flaskangular'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_CONFIG_FILE=config/staging.py
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/flaskangular_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@localhost:5432/flaskangular_test
    depends_on:
      flaskangular-db:
        condition: service_healthy
    links:
      - "flaskangular-db"
