version: '2.0'

services:

  asdf-db:
    container_name: asdf-db
    build: ./asdf/db
    ports:
      - 5435:5432 # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  users-service:
    container_name: asdf-service
    build: .
    volumes:
      - '.:/usr/src/asdf'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=asdf.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres@asdf-db:5432/asdf_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@asdf-db:5432/asdf_test
    depends_on:
      users-db:
        condition: service_healthy
      links:
        - asdf-db
