branch-defaults:
  dev:
    environment: flask-env
    group_suffix: null
environment-defaults:
  flask-env:
    branch: dev
    repository: flaskangular
global:
  application_name: flaskangular
  branch: dev
  default_ec2_keyname: aws-eb
  default_platform: python
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: flaskangular
  sc: git
  workspace_type: Application
